<a href="https://colab.research.google.com/github/rodriguez8hans/IAUEES/blob/main/03_Machine_Learning_Basico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Verificar si estamos en Google Colab
try:
    import google.colab
    IN_COLAB = True
    print(" Ejecutándose en Google Colab")
except ImportError:
    IN_COLAB = False
    print(" No está en Google Colab")

# Verificar recursos disponibles en Colab
if IN_COLAB:
    # Verificar GPU disponible
    import tensorflow as tf
    print(" Verificando recursos de hardware:")
    print(f"   - GPUs disponibles: {len(tf.config.list_physical_devices('GPU'))}")

    if len(tf.config.list_physical_devices('GPU')) > 0:
        print("   - Tipo GPU:", tf.config.list_physical_devices('GPU')[0])
        print("    GPU activada - Ideal para Deep Learning")
    else:
        print("     Solo CPU disponible - Suficiente para esta práctica")

    # Verificar RAM disponible
    import psutil
    ram_gb = round(psutil.virtual_memory().total / (1024**3), 1)
    print(f"   - RAM disponible: {ram_gb} GB")
    print(f"   - Almacenamiento temporal: ~100GB")

# Instalar librerías adicionales específicas para Colab
if IN_COLAB:
    print("\n Instalando librerías adicionales en Colab...")
    !pip install -q plotly kaleido  # Para gráficos interactivos
    !pip install -q seaborn --upgrade  # Asegurar última versión
    print(" Instalación completada")

 Ejecutándose en Google Colab
 Verificando recursos de hardware:
   - GPUs disponibles: 0
     Solo CPU disponible - Suficiente para esta práctica
   - RAM disponible: 12.7 GB
   - Almacenamiento temporal: ~100GB

 Instalando librerías adicionales en Colab...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.5/51.5 kB 594.4 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.3/51.3 kB 1.4 MB/s eta 0:00:00
 Instalación completada


In [2]:
# Importaciones optimizadas para Colab
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Importaciones específicas para ML/DL
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

# Configuración específica para Colab
import warnings
warnings.filterwarnings('ignore')

# Configuración de visualización optimizada para Colab
plt.style.use('default')
sns.set_palette("husl")
plt.rcParams['figure.figsize'] = (12, 8)  # Más grande para pantallas Colab
plt.rcParams['font.size'] = 12
plt.rcParams['figure.dpi'] = 100  # Mejor resolución en Colab

# Configurar plotly para Colab
import plotly.io as pio
pio.renderers.default = 'colab'  # Renderizado específico para Colab

print("\n Configuración específica para Google Colab completada")
print("=" * 60)


 Configuración específica para Google Colab completada


In [3]:
def conectar_google_drive():
    """Función para conectar con Google Drive en Colab"""
    if IN_COLAB:
        from google.colab import drive
        try:
            drive.mount('/content/drive')
            print(" Google Drive conectado exitosamente")
            return True
        except Exception as e:
            print(f" Error conectando Google Drive: {e}")
            return False
    else:
        print(" Esta función solo funciona en Google Colab")
        return False



def mostrar_grafico_interactivo(fig):
    """Mostrar gráficos Plotly optimizados para Colab"""
    if IN_COLAB:
        fig.show()
    else:
        fig.show(renderer='browser')

In [4]:
# Opción 2: Cargar desde URL (aprovechando conectividad de Colab)
print("\nMétodo 2: Cargar desde URL")
try:
    # Dataset de vinos desde UCI
    wine_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
    wine_columns = ['class', 'alcohol', 'malic_acid', 'ash', 'alcalinity', 'magnesium',
                   'phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins',
                   'color_intensity', 'hue', 'od280', 'proline']

    wine_df = pd.read_csv(wine_url, names=wine_columns)
    print(f" Wine dataset desde UCI: {wine_df.shape}")
except Exception as e:
    print(f" No se pudo cargar dataset desde URL: {e}")
    wine_df = None


Método 2: Cargar desde URL
 Wine dataset desde UCI: (178, 14)


In [5]:
# ========================================================================
# CARGAR DATOS ESPECÍFICO PARA COLAB
# ========================================================================

print("\n CARGANDO DATOS EN GOOGLE COLAB")
print("=" * 40)

# Opción 1: Datasets integrados en Colab (más rápido)
print("Método 1: Datasets integrados en Seaborn")
titanic = sns.load_dataset('titanic')
tips = sns.load_dataset('tips')
flights = sns.load_dataset('flights')

print(f" Titanic dataset: {titanic.shape}")
print(f" Tips dataset: {tips.shape}")
print(f" Flights dataset: {flights.shape}")


 CARGANDO DATOS EN GOOGLE COLAB
Método 1: Datasets integrados en Seaborn
 Titanic dataset: (891, 15)
 Tips dataset: (244, 7)
 Flights dataset: (144, 3)


## Cargar y preparar datos de ejemplo

Seleccionar un dataset adecuado para tareas de clasificación y otro para regresión. Realizar la división en conjuntos de entrenamiento y prueba, y aplicar escalado si es necesario.


In [6]:
# 1. Seleccionar el dataset wine_df para clasificación
X = wine_df.drop('class', axis=1)
y = wine_df['class']

# 2. Dividir el dataset de clasificación
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Dataset de clasificación dividido:")
print(f"  - Entrenamiento: {X_train.shape}, {y_train.shape}")
print(f"  - Prueba: {X_test.shape}, {y_test.shape}")

# 3. Seleccionar el dataset tips para regresión
X_reg = tips.drop('tip', axis=1)
y_reg = tips['tip']

# 4. Dividir el dataset de regresión
X_reg_train, X_reg_test, y_reg_train, y_reg_test = train_test_split(X_reg, y_reg, test_size=0.2, random_state=42)
print("\nDataset de regresión dividido:")
print(f"  - Entrenamiento: {X_reg_train.shape}, {y_reg_train.shape}")
print(f"  - Prueba: {X_reg_test.shape}, {y_reg_test.shape}")

# 5. Identificar columnas numéricas en el dataset de regresión de entrenamiento
numeric_cols_reg = X_reg_train.select_dtypes(include=np.number).columns
print(f"\nColumnas numéricas para escalado en regresión: {list(numeric_cols_reg)}")

# 6. Inicializar un StandardScaler
scaler = StandardScaler()

# 7. Aplicar el escalador a las columnas numéricas
X_reg_train[numeric_cols_reg] = scaler.fit_transform(X_reg_train[numeric_cols_reg])
X_reg_test[numeric_cols_reg] = scaler.transform(X_reg_test[numeric_cols_reg])

print("\nEscalado aplicado a las columnas numéricas del dataset de regresión.")
display(X_reg_train.head())

Dataset de clasificación dividido:
  - Entrenamiento: (142, 13), (142,)
  - Prueba: (36, 13), (36,)

Dataset de regresión dividido:
  - Entrenamiento: (195, 6), (195,)
  - Prueba: (49, 6), (49,)

Columnas numéricas para escalado en regresión: ['total_bill', 'size']

Escalado aplicado a las columnas numéricas del dataset de regresión.


total_bill   sex smoker   day    time      size
228   -0.793062  Male     No   Sat  Dinner -0.612141
208    0.463227  Male    Yes   Sat  Dinner -0.612141
96     0.807307  Male    Yes   Fri  Dinner -0.612141
167    1.313709  Male     No   Sun  Dinner  1.519421
84    -0.484419  Male     No  Thur   Lunch -0.612141

## Modelos de clasificación

Implementar y entrenar varios modelos de clasificación (ej: Logistic Regression, SVM, RandomForest) en el dataset de clasificación.


In [10]:

lr_model = LogisticRegression(random_state=42)
lr_model.fit(X_train, y_train)
print("Modelo de Regresión Logística entrenado.")


svc_model = SVC(random_state=42)
svc_model.fit(X_train, y_train)
print("Modelo de SVC entrenado.")


rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
print("Modelo de RandomForestClassifier entrenado.")

Modelo de Regresión Logística entrenado.
Modelo de SVC entrenado.
Modelo de RandomForestClassifier entrenado.


## Evaluación de modelos de clasificación

Evaluar el rendimiento de los modelos de clasificación utilizando métricas como precisión, matriz de confusión y reporte de clasificación.


In [8]:
# 1. Predecir las etiquetas para el conjunto de prueba X_test
lr_pred = lr_model.predict(X_test)
svc_pred = svc_model.predict(X_test)
rf_pred = rf_model.predict(X_test)

# 2. Evaluar y imprimir métricas para cada modelo
print("Evaluación del Modelo de Regresión Logística:")
print(f"Precisión: {accuracy_score(y_test, lr_pred):.4f}")
print("Matriz de Confusión:\n", confusion_matrix(y_test, lr_pred))
print("Reporte de Clasificación:\n", classification_report(y_test, lr_pred))

print("\n" + "="*50 + "\n")

print("Evaluación del Modelo de SVC:")
print(f"Precisión: {accuracy_score(y_test, svc_pred):.4f}")
print("Matriz de Confusión:\n", confusion_matrix(y_test, svc_pred))
print("Reporte de Clasificación:\n", classification_report(y_test, svc_pred))

print("\n" + "="*50 + "\n")

print("Evaluación del Modelo de RandomForestClassifier:")
print(f"Precisión: {accuracy_score(y_test, rf_pred):.4f}")
print("Matriz de Confusión:\n", confusion_matrix(y_test, rf_pred))
print("Reporte de Clasificación:\n", classification_report(y_test, rf_pred))

Evaluación del Modelo de Regresión Logística:
Precisión: 0.9722
Matriz de Confusión:
 [[13  1  0]
 [ 0 14  0]
 [ 0  0  8]]
Reporte de Clasificación:
               precision    recall  f1-score   support

           1       1.00      0.93      0.96        14
           2       0.93      1.00      0.97        14
           3       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36



Evaluación del Modelo de SVC:
Precisión: 0.8056
Matriz de Confusión:
 [[14  0  0]
 [ 0 11  3]
 [ 0  4  4]]
Reporte de Clasificación:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       0.73      0.79      0.76        14
           3       0.57      0.50      0.53         8

    accuracy                           0.81        36
   macro avg       0.77      0.76      0.76        36
weighte

## Modelos de regresión

Implementar y entrenar varios modelos de regresión (ej: Linear Regression, RandomForestRegressor, SVR) en el dataset de regresión.


In [12]:
# 1. Inicializar y entrenar el modelo Linear Regression
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de Regresión Lineal entrenado.")

# 2. Inicializar y entrenar el modelo RandomForestRegressor
rf_reg_model = RandomForestRegressor(random_state=42)
rf_reg_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de RandomForestRegressor entrenado.")

# 3. Inicializar y entrenar el modelo SVR
svr_model = SVR()
svr_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de SVR entrenado.")

print("\nLos modelos de regresión han sido entrenados.")

Modelo de Regresión Lineal entrenado.
Modelo de RandomForestRegressor entrenado.
Modelo de SVR entrenado.

Los modelos de regresión han sido entrenados.


In [14]:
# Importar las clases de modelos de regresión necesarias
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

# 1. Inicializar y entrenar el modelo Linear Regression
linear_reg_model = LinearRegression()
linear_reg_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de Regresión Lineal entrenado.")

# 2. Inicializar y entrenar el modelo RandomForestRegressor
rf_reg_model = RandomForestRegressor(random_state=42)
rf_reg_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de RandomForestRegressor entrenado.")

# 3. Inicializar y entrenar el modelo SVR
svr_model = SVR()
svr_model.fit(X_reg_train.select_dtypes(include=np.number), y_reg_train) # Select only numeric columns for training
print("Modelo de SVR entrenado.")

print("\nLos modelos de regresión han sido entrenados.")

Modelo de Regresión Lineal entrenado.
Modelo de RandomForestRegressor entrenado.
Modelo de SVR entrenado.

Los modelos de regresión han sido entrenados.


## Evaluación de modelos de regresión


Evaluar el rendimiento de los modelos de regresión utilizando métricas como Error Cuadrático Medio (MSE), Error Absoluto Medio (MAE) y R².


In [16]:
# 1. Select only numeric columns from X_reg_test for prediction
X_reg_test_numeric = X_reg_test.select_dtypes(include=np.number)

# 2. Predecir los valores para el conjunto de prueba X_reg_test utilizando cada modelo
linear_reg_pred = linear_reg_model.predict(X_reg_test_numeric)
rf_reg_pred = rf_reg_model.predict(X_reg_test_numeric)
svr_pred = svr_model.predict(X_reg_test_numeric)

# 3. Importar las métricas de evaluación (ya importadas en una celda anterior)

# 4. Calcular y imprimir las métricas para el modelo Linear Regression
print("Evaluación del Modelo de Regresión Lineal:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, linear_reg_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, linear_reg_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, linear_reg_pred):.4f}")

print("\n" + "="*50 + "\n")

# 5. Calcular y imprimir las métricas para el modelo RandomForestRegressor
print("Evaluación del Modelo de RandomForestRegressor:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, rf_reg_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, rf_reg_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, rf_reg_pred):.4f}")

print("\n" + "="*50 + "\n")

# 6. Calcular y imprimir las métricas para el modelo SVR
print("Evaluación del Modelo de SVR:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, svr_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, svr_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, svr_pred):.4f}")

Evaluación del Modelo de Regresión Lineal:
  - Error Cuadrático Medio (MSE): 0.6486
  - Error Absoluto Medio (MAE): 0.6639
  - R²: 0.4811


Evaluación del Modelo de RandomForestRegressor:
  - Error Cuadrático Medio (MSE): 0.8267
  - Error Absoluto Medio (MAE): 0.7285
  - R²: 0.3386


Evaluación del Modelo de SVR:
  - Error Cuadrático Medio (MSE): 0.5727
  - Error Absoluto Medio (MAE): 0.5911
  - R²: 0.5418


In [17]:
# Importar las métricas de evaluación necesarias
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# 1. Select only numeric columns from X_reg_test for prediction
X_reg_test_numeric = X_reg_test.select_dtypes(include=np.number)

# 2. Predecir los valores para el conjunto de prueba X_reg_test utilizando cada modelo
linear_reg_pred = linear_reg_model.predict(X_reg_test_numeric)
rf_reg_pred = rf_reg_model.predict(X_reg_test_numeric)
svr_pred = svr_model.predict(X_reg_test_numeric)

# 3. Calcular y imprimir las métricas para el modelo Linear Regression
print("Evaluación del Modelo de Regresión Lineal:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, linear_reg_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, linear_reg_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, linear_reg_pred):.4f}")

print("\n" + "="*50 + "\n")

# 4. Calcular y imprimir las métricas para el modelo RandomForestRegressor
print("Evaluación del Modelo de RandomForestRegressor:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, rf_reg_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, rf_reg_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, rf_reg_pred):.4f}")

print("\n" + "="*50 + "\n")

# 5. Calcular y imprimir las métricas para el modelo SVR
print("Evaluación del Modelo de SVR:")
print(f"  - Error Cuadrático Medio (MSE): {mean_squared_error(y_reg_test, svr_pred):.4f}")
print(f"  - Error Absoluto Medio (MAE): {mean_absolute_error(y_reg_test, svr_pred):.4f}")
print(f"  - R²: {r2_score(y_reg_test, svr_pred):.4f}")

Evaluación del Modelo de Regresión Lineal:
  - Error Cuadrático Medio (MSE): 0.6486
  - Error Absoluto Medio (MAE): 0.6639
  - R²: 0.4811


Evaluación del Modelo de RandomForestRegressor:
  - Error Cuadrático Medio (MSE): 0.8267
  - Error Absoluto Medio (MAE): 0.7285
  - R²: 0.3386


Evaluación del Modelo de SVR:
  - Error Cuadrático Medio (MSE): 0.5727
  - Error Absoluto Medio (MAE): 0.5911
  - R²: 0.5418


## Comparación de algoritmos


Comparar los resultados de los diferentes modelos de clasificación y regresión para determinar cuál funciona mejor en cada caso.


In [18]:
# Análisis y comparación de modelos de clasificación

print("==================================================")
print("Comparación de Modelos de Clasificación")
print("==================================================")

# Métricas de clasificación obtenidas en el paso anterior
lr_accuracy = accuracy_score(y_test, lr_pred)
svc_accuracy = accuracy_score(y_test, svc_pred)
rf_accuracy = accuracy_score(y_test, rf_pred)

print(f"Precisión del Modelo de Regresión Logística: {lr_accuracy:.4f}")
print(f"Precisión del Modelo de SVC: {svc_accuracy:.4f}")
print(f"Precisión del Modelo de RandomForestClassifier: {rf_accuracy:.4f}")

print("\nAnálisis de Reportes de Clasificación:")
print("Regresión Logística:\n", classification_report(y_test, lr_pred))
print("SVC:\n", classification_report(y_test, svc_pred))
print("RandomForestClassifier:\n", classification_report(y_test, rf_pred))

# Determinar el mejor modelo de clasificación
classification_accuracies = {
    'Regresión Logística': lr_accuracy,
    'SVC': svc_accuracy,
    'RandomForestClassifier': rf_accuracy
}
best_classification_model = max(classification_accuracies, key=classification_accuracies.get)
print(f"\nEl mejor modelo de clasificación basado en la precisión es: {best_classification_model}")

# Análisis y comparación de modelos de regresión

print("\n==================================================")
print("Comparación de Modelos de Regresión")
print("==================================================")

# Métricas de regresión obtenidas en el paso anterior
# Asegurarse de usar las predicciones correctas para cada modelo
# Las predicciones ya fueron calculadas en el paso anterior: linear_reg_pred, rf_reg_pred, svr_pred

linear_reg_mse = mean_squared_error(y_reg_test, linear_reg_pred)
linear_reg_mae = mean_absolute_error(y_reg_test, linear_reg_pred)
linear_reg_r2 = r2_score(y_reg_test, linear_reg_pred)

rf_reg_mse = mean_squared_error(y_reg_test, rf_reg_pred)
rf_reg_mae = mean_absolute_error(y_reg_test, rf_reg_pred)
rf_reg_r2 = r2_score(y_reg_test, rf_reg_pred)

svr_mse = mean_squared_error(y_reg_test, svr_pred)
svr_mae = mean_absolute_error(y_reg_test, svr_pred)
svr_r2 = r2_score(y_reg_test, svr_pred)


print(f"Métricas del Modelo de Regresión Lineal:")
print(f"  - MSE: {linear_reg_mse:.4f}")
print(f"  - MAE: {linear_reg_mae:.4f}")
print(f"  - R²: {linear_reg_r2:.4f}")

print("\n" + "-"*30 + "\n")

print(f"Métricas del Modelo de RandomForestRegressor:")
print(f"  - MSE: {rf_reg_mse:.4f}")
print(f"  - MAE: {rf_reg_mae:.4f}")
print(f"  - R²: {rf_reg_r2:.4f}")

print("\n" + "-"*30 + "\n")

print(f"Métricas del Modelo de SVR:")
print(f"  - MSE: {svr_mse:.4f}")
print(f"  - MAE: {svr_mae:.4f}")
print(f"  - R²: {svr_r2:.4f}")


# Determinar el mejor modelo de regresión (menor MSE/MAE, mayor R²)
regression_metrics = {
    'Linear Regression': {'MSE': linear_reg_mse, 'MAE': linear_reg_mae, 'R²': linear_reg_r2},
    'RandomForestRegressor': {'MSE': rf_reg_mse, 'MAE': rf_reg_mae, 'R²': rf_reg_r2},
    'SVR': {'MSE': svr_mse, 'MAE': svr_mae, 'R²': svr_r2}
}

# En regresión, buscamos el menor MSE/MAE y el mayor R²
# Podemos basarnos principalmente en R² para simplicidad en la comparación general
best_regression_model = max(regression_metrics, key=lambda k: regression_metrics[k]['R²'])
print(f"\nEl mejor modelo de regresión basado en R² es: {best_regression_model}")

# Resumen de la comparación
print("\n==================================================")
print("Resumen de la Comparación de Modelos")
print("==================================================")
print(f"Para la tarea de clasificación, el modelo con mejor rendimiento fue el {best_classification_model}, alcanzando una precisión de {classification_accuracies[best_classification_model]:.4f}.")
print(f"Esto se justifica por su alta precisión general y su capacidad para clasificar correctamente la mayoría de las instancias en cada clase, como se observa en el reporte de clasificación.")

print(f"\nPara la tarea de regresión, el modelo con mejor rendimiento fue el {best_regression_model}.")
print(f"Este modelo presentó el menor Error Cuadrático Medio (MSE de {regression_metrics[best_regression_model]['MSE']:.4f}) y Error Absoluto Medio (MAE de {regression_metrics[best_regression_model]['MAE']:.4f}), y el mayor coeficiente R² ({regression_metrics[best_regression_model]['R²']:.4f}).")
print("Esto indica que sus predicciones están, en promedio, más cerca de los valores reales de la propina y que explica una mayor proporción de la variabilidad de los datos.")

Comparación de Modelos de Clasificación
Precisión del Modelo de Regresión Logística: 0.9722
Precisión del Modelo de SVC: 0.8056
Precisión del Modelo de RandomForestClassifier: 1.0000

Análisis de Reportes de Clasificación:
Regresión Logística:
               precision    recall  f1-score   support

           1       1.00      0.93      0.96        14
           2       0.93      1.00      0.97        14
           3       1.00      1.00      1.00         8

    accuracy                           0.97        36
   macro avg       0.98      0.98      0.98        36
weighted avg       0.97      0.97      0.97        36

SVC:
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       0.73      0.79      0.76        14
           3       0.57      0.50      0.53         8

    accuracy                           0.81        36
   macro avg       0.77      0.76      0.76        36
weighted avg       0.80      0.81      0.8

## Visualización de resultados




In [19]:
# 1. Crear un DataFrame de Pandas para almacenar las métricas de precisión de los modelos de clasificación.
classification_metrics_df = pd.DataFrame({
    'Modelo': classification_accuracies.keys(),
    'Precisión': classification_accuracies.values()
})

# 2. Utilizar Plotly Express para crear un gráfico de barras que compare las precisiones.
fig_classification = px.bar(
    classification_metrics_df,
    x='Modelo',
    y='Precisión',
    title='Comparación de Precisión de Modelos de Clasificación'
)

# 3. Mostrar el gráfico de barras utilizando la función mostrar_grafico_interactivo.
mostrar_grafico_interactivo(fig_classification)

In [20]:
# 4. Crear un DataFrame de Pandas para almacenar las métricas de regresión (MSE, MAE, R²).
regression_metrics_df = pd.DataFrame({
    'Métrica': ['MSE', 'MAE', 'R²'],
    'Linear Regression': [linear_reg_mse, linear_reg_mae, linear_reg_r2],
    'RandomForestRegressor': [rf_reg_mse, rf_reg_mae, rf_reg_r2],
    'SVR': [svr_mse, svr_mae, svr_r2]
})

# Reorganizar el DataFrame para facilitar la visualización comparativa por métrica
regression_metrics_melted = regression_metrics_df.melt(
    id_vars='Métrica',
    var_name='Modelo',
    value_name='Valor'
)

# 5. Utilizar Plotly Express para crear gráficos de barras comparativos para cada métrica de regresión.
fig_regression = px.bar(
    regression_metrics_melted,
    x='Modelo',
    y='Valor',
    color='Modelo',
    facet_col='Métrica',
    facet_col_wrap=3, # Mostrar las 3 métricas en columnas separadas
    title='Comparación de Métricas de Modelos de Regresión (MSE, MAE, R²)',
    labels={'Valor': 'Valor de la Métrica'} # Etiqueta del eje y más descriptiva
)

# Ajustar el diseño para mejor visualización
fig_regression.update_layout(
    # Permitir que los títulos de las facetas se muestren correctamente
    annotations=[
        dict(
            text='MSE', x=0.03, y=1.08, xref='paper', yref='paper', showarrow=False, font=dict(size=14)
        ),
        dict(
            text='MAE', x=0.5, y=1.08, xref='paper', yref='paper', showarrow=False, font=dict(size=14)
        ),
        dict(
            text='R²', x=0.97, y=1.08, xref='paper', yref='paper', showarrow=False, font=dict(size=14)
        )
    ],
    margin=dict(t=50), # Espacio superior para el título principal
    showlegend=True # Mostrar leyenda para los modelos
)

# Invertir el eje y para MSE y MAE si se desea mostrar que menor es mejor
# No se hace automáticamente con facet_col, se requeriría un enfoque diferente o subplots manuales.
# Para este caso, la visualización con barras ascendentes para MSE/MAE y R2 es informativa.

# 6. Mostrar los gráficos de barras de regresión utilizando la función mostrar_grafico_interactivo.
mostrar_grafico_interactivo(fig_regression)

In [ ]:

from google.colab import auth
auth.authenticate_user()


!git config --global user.email "andy.rodriguez@uees.edu.ec"
!git config --global user.name "Hans"

token = "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"
repo_url = f"https://{token}@github.com/rodriguez8hans/IAUEES.git"


!rm -rf IAUEES


!git clone {repo_url}
%cd IAUEES

!mkdir -p 02_Laboratorio/notebooks


!cp /content/03_Machine_Learning_Basico.ipynb 02_Laboratorio/notebooks/


!git add .
!git commit -m "Añadir notebook de fundamentos"
!git push origin main
